version: "3.0"
services:
  negotiated-rates-server:
    container_name: negotiated-rates-service
    restart: always
    network_mode: host
    user: root
    build: .
    ports:
      - "8085:8085"
#    networks:
#      - spring-cloud-network
    volumes:
      - /var/logs:/logs

#networks:
#  spring-cloud-network:
#    driver: bridge