spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.datasource.username=abconnect
spring.datasource.password=abconnect
spring.datasource.url=jdbc:postgresql://10.10.6.3:5433/abconnect?createDatabaseIfNotExist=true

params.keycloak.config.token-url=https://keycloakuat.abcthebank.com:8099/realms/KRAITAXREALM/protocol/openid-connect/token
params.keycloak.config.clientid=kra-api