spring.profiles.active=prod
server.port=8090

spring.mail.host=172.16.2.60
spring.mail.port=25
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

app.config.param.smtphost=172.16.2.60
app.config.param.email-from=ictsupport@abcthebank.com

logging.file.name=/logs/negotiated-rates/applogs-negotiated.log
logging.logback.rollingpolicy.max-history=100