server.port=8090
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.generate-ddl=true
spring.datasource.username=rate_request_user
spring.datasource.password=iNt3rn@l
spring.datasource.url=jdbc:postgresql://172.14.0.136:5432/negotiated_rates?createDatabaseIfNotExist=true


params.keycloak.config.token-url=https://keycloakuat.abcthebank.com:8099/realms/KRAITAXREALM/protocol/openid-connect/token
params.keycloak.config.clientid=kra-api