# Production profile configuration for Negotiated Rates.
#
# This profile contains production database and security settings for
# deployment environments.

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.generate-ddl=true
spring.datasource.username=devops
spring.datasource.password=devops
spring.datasource.url=jdbc:postgresql://10.10.2.9:5432/abconnect_api_db?createDatabaseIfNotExist=true

# Keycloak OAuth2 settings used to request tokens and validate JWTs in production.
params.keycloak.config.token-url=https://keycloakuat.abcthebank.com:8099/realms/KRAITAXREALM/protocol/openid-connect/token
params.keycloak.config.clientid=kra-api